sudo: required

before_install:
    - docker build -f Dockerfile.dev -t abijeethdarwin/docker-react .

script:
    - docker run -e CI=true abijeethdarwin/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-377733686601"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_SECRET_KEY
    